### PR TITLE
Add suiteFullName property to test related events.

### PR DESCRIPTION
**Pull request by Saulis**
Needed for identifying events in for example test reporting.

### CODE REVIEW

**Comment by Saulis** [comment]
If needed, I'll rebase this after #127 is merged.

**Comment by SevInf** [comment]
cc @hatroman
There is two very similar pull requests now: this one and #136. The difference is that #136 adds full name as array of simple suite names and this one adds it as string. I don't think we should have both. In fact  I think that now when reporters and plugins needs more and more information from the suite will be more convinient to pass just the  `Suite` instance.

What do you guys think?

**Comment by Saulis** [comment]
Passing the whole Suite could be the way to go. I think I actually saw one event somewhere that alredy did?

**Comment by SevInf** [comment]
No, there is no such event for reporters now, but users may get Suite instances with API.

For now, I've merged #136, because it is required for further parallelization imporvements in next version. 
c5224c0568eb3a04f0fa5cb87234907686189590 adds `suite` and `state` properties to the reporters while keeping existing `suiteXXX` fields for backward compatibility. Somewhen before the next release (when `gui` and reporters will be updated to use new fileds) I'm going to remove this extra fields and keep only `suite`, `state` and `browserId`. 

You may now use `suite.fullName` in your reporters, so I will close this for now. Feel free to reopen if you really need this merged and proposed solution does not work for you.

**Pull request closed without merging**
