### PR TITLE
TeamCity reporter

### PR DESCRIPTION
**Pull request by shuhrat**
Tried to revert the commit that removed TeamCity reporter, added ignoreSuire state, and modified suite filtering logic

@SevInf plz

### CODE REVIEW

**Comment by anton-rudeshko** [comment]
:deciduous_tree:

**Comment by SevInf** [comment]
Also, Travis build [fails on jscs](https://travis-ci.org/bem/gemini/jobs/48769693#L227-L235).
You can run jshint and jscs locally with `npm run lint`

**Comment by SevInf** [comment]
Now `html` report is broken. For the same suites as above:

```js
gemini.suite('button', function(suite) {
  gemini.suite('normal', function() {
  });
});
```

`gemini test --grep normal --reporter html`

Produces the following tree in report:

```
+ normal
   + state 1
   + state 2
   ....
```

While the expected output is:

```
+ button
  + normal
     + state 1
     + state 2
     ....
```

**Comment by Shuhrat** [comment]
OMG
I'm near to give up, hence don't know how to resolve:
1) I didn't catch the point =(
2) `grep` functionality is designed badly

**Comment by SevInf** [comment]
Yes, I agree with your point about `grep` design. Now I'm thinking that implementing filter during the loading of the suites instead of the `Runner` will be much better will resolve all of the issues we have with reporters.

**Comment by Shuhrat** [comment]
That would be great!

**Pull request closed without merging**
